return{

	Auto = false;
	BaseDamage = 85;
	FireRate = 2; --In second
	ReloadTime = 4; --In second
	AmmoPerMag = 6; --Put "math.huge" to make this gun has infinite ammo and never reload
	CurrentAmmo = 200;
	CameraRecoilingEnabled = true;
	Recoil = 60;
	AngleX_Min = 1; --In degree
	AngleX_Max = 2; --In degree
	AngleY_Min = 1; --In degree
	AngleY_Max = 2; --In degree
	AngleZ_Min = -1; --In degree
	AngleZ_Max = 1; --In degree
	Accuracy = 0.1; --In percent. For example: 0.5 is 50%
	RecoilSpeed = 15; 
	RecoilDamper = 0.50;
	RecoilRedution = 0.2; --In percent.

}