local REALISM_CONFIG = {
	HeadMovementEnabled = true,

	MaterialMap = {
		Mud = "Dirt",
		Pebble = "Dirt",
		Ground = "Dirt",

		Sand = "Sand",
		Snow = "Sand",
		Sandstone = "Sand",

		Rock = "Gravel",
		Basalt = "Gravel",
		Asphalt = "Gravel",
		Glacier = "Gravel",
		Slate = "Gravel",

		WoodPlanks = "Wood",
		LeafyGrass = "Grass",

		Ice = "Marble",
		Salt = "Marble",
		Marble = "Marble",
		Pavement = "Marble",
		Limestone = "Marble",

		Foil = "Metal",
		DiamondPlate = "Metal",
		CorrodedMetal = "Metal",
	},

	RotationFactors = {
		Head = {
			Pitch = 0.8,
			Yaw = 0.75,
		},
	},
}

return REALISM_CONFIG
