return {
	CoconutSyrup = {
		ID = "CoconutSyrup",
		LiquidColor = Color3.new(0.98, 0.96, 0.92),
		Volume = 25,
		Type = "Coffee",
	},
	CaramelSyrup = {
		ID = "CaramelSyrup",
		LiquidColor = Color3.new(0.72, 0.45, 0.20),
		Volume = 25,
		Type = "Coffee",
	},
	VanillaSyrup = {
		ID = "VanillaSyrup",
		LiquidColor = Color3.new(0.95, 0.90, 0.75),
		Volume = 25,
		Type = "Coffee",
	},
	StrawberrySyrup = {
		ID = "StrawberrySyrup",
		LiquidColor = Color3.new(0.9, 0.25, 0.35),
		Volume = 25,
		Type = "Coffee",
	},
	HazelnutSyrup = {
		ID = "HazelnutSyrup",
		LiquidColor = Color3.new(0.65, 0.50, 0.35),
		Volume = 25,
		Type = "Coffee",
	},

	Matcha = {
		ID = "Matcha",
		LiquidColor = Color3.new(0.141176, 0.372549, 0.192156),
		Volume = 25,
		Type = "Coffee",
	},

	Coffee = {
		ID = "Coffee",
		LiquidColor = Color3.new(0.2, 0.1, 0.08),
		Volume = 25,
		Type = "Coffee",
	},
	Espresso = {
		ID = "Espresso",
		LiquidColor = Color3.new(0.15, 0.08, 0.03),
		Volume = 25,
		Type = "Coffee",
	},
	Milk = {
		ID = "Milk",
		LiquidColor = Color3.new(0.95, 0.95, 0.92),
		Volume = 25,
		Type = "Coffee",
	},
	Cream = {
		ID = "Cream",
		LiquidColor = Color3.new(0.98, 0.96, 0.88),
		Volume = 15,
		Type = "Coffee",
		IsTopping = true,
	},
}