const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("abraxius", Object.freeze({
  health: () => ipcRenderer.invoke("health"),
  events: (limit) => ipcRenderer.invoke("events", limit),
  pending: () => ipcRenderer.invoke("pending"),
  runCli: (args) => ipcRenderer.invoke("run-cli", args),
  restartHost: () => ipcRenderer.invoke("restart-host"),
  openLog: () => ipcRenderer.invoke("open-log"),
  openData: () => ipcRenderer.invoke("open-data"),
  getAutostart: () => ipcRenderer.invoke("autostart-status"),
  setAutostart: (enabled) => ipcRenderer.invoke("autostart", enabled),
  antigravity: Object.freeze({
    status: () => ipcRenderer.invoke("antigravity-status"),
    start: (options) => ipcRenderer.invoke("antigravity-start", options),
    prompt: (prompt, options) => ipcRenderer.invoke("antigravity-prompt", prompt, options),
    setWriteAccess: (enabled) => ipcRenderer.invoke("antigravity-permissions", enabled),
    restart: () => ipcRenderer.invoke("antigravity-restart"),
    interrupt: () => ipcRenderer.invoke("antigravity-interrupt"),
    stop: () => ipcRenderer.invoke("antigravity-stop"),
    write: (data) => ipcRenderer.invoke("antigravity-write", data),
    onEvent: (callback) => ipcRenderer.on("antigravity-event", (_event, value) => callback(value)),
  }),
  memory: Object.freeze({
    health: () => ipcRenderer.invoke("memory-health"),
    search: (query, projectId) => ipcRenderer.invoke("memory-search", query, projectId),
    records: (scope, type, projectId, status) => ipcRenderer.invoke("memory-records", scope, type, projectId, status),
    add: (data) => ipcRenderer.invoke("memory-add", data),
    correct: (payload) => ipcRenderer.invoke("memory-correct", payload),
    forget: (id) => ipcRenderer.invoke("memory-forget", id),
    proposed: (projectId) => ipcRenderer.invoke("memory-proposed", projectId),
    approve: (id) => ipcRenderer.invoke("memory-approve", id),
    reject: (id) => ipcRenderer.invoke("memory-reject", id),
    brief: (projectId) => ipcRenderer.invoke("memory-brief", projectId),
    getSettings: () => ipcRenderer.invoke("memory-settings-get"),
    saveSettings: (settings) => ipcRenderer.invoke("memory-settings-save", settings),
    indexDir: (dirPath) => ipcRenderer.invoke("memory-index-dir", dirPath),
  }),
  ollama: Object.freeze({
    status: () => ipcRenderer.invoke("ollama-status"),
    models: (endpoint) => ipcRenderer.invoke("ollama-models", endpoint),
    pull: (payload) => ipcRenderer.invoke("ollama-pull", payload),
    cancelPull: (pullId) => ipcRenderer.invoke("ollama-pull-cancel", pullId),
    onPullProgress: (callback) => ipcRenderer.on("ollama-pull-progress", (_event, data) => callback(data)),
    chat: (payload) => ipcRenderer.invoke("ollama-chat", payload),
    agent: (payload) => ipcRenderer.invoke("ollama-agent", payload),
    cancel: (sessionId) => ipcRenderer.invoke("ollama-cancel", sessionId),
    getSettings: () => ipcRenderer.invoke("ollama-settings-get"),
    saveSettings: (settings) => ipcRenderer.invoke("ollama-settings-save", settings),
    onChunk: (callback) => ipcRenderer.on("ollama-chunk", (_event, data) => callback(data)),
    onAgentStatus: (callback) => ipcRenderer.on("ollama-agent-status", (_event, data) => callback(data)),
    onChatStart: (callback) => ipcRenderer.on("ollama-chat-start", (_event, data) => callback(data)),
    onResearch: (callback) => ipcRenderer.on("ollama-research", (_event, data) => callback(data)),
    ptyStatus: () => ipcRenderer.invoke("ollama-pty-status"),
    ptyStart: (options) => ipcRenderer.invoke("ollama-pty-start", options),
    ptyRestart: (options) => ipcRenderer.invoke("ollama-pty-restart", options),
    ptyStop: () => ipcRenderer.invoke("ollama-pty-stop"),
    ptyInterrupt: () => ipcRenderer.invoke("ollama-pty-interrupt"),
    ptyWrite: (data) => ipcRenderer.invoke("ollama-pty-write", data),
    onPtyEvent: (callback) => ipcRenderer.on("ollama-pty-event", (_event, value) => callback(value)),
  }),
  nvidiaNim: Object.freeze({
    status: () => ipcRenderer.invoke("nvidia-nim-status"),
    getSettings: () => ipcRenderer.invoke("nvidia-nim-settings-get"),
    saveSettings: (settings) => ipcRenderer.invoke("nvidia-nim-settings-save", settings),
    chat: (payload) => ipcRenderer.invoke("nvidia-nim-chat", payload),
    cancel: (sessionId) => ipcRenderer.invoke("nvidia-nim-cancel", sessionId),
    onReasoning: (callback) => ipcRenderer.on("nvidia-nim-reasoning", (_event, data) => callback(data)),
    onChunk: (callback) => ipcRenderer.on("nvidia-nim-chunk", (_event, data) => callback(data)),
    onChatStart: (callback) => ipcRenderer.on("nvidia-nim-chat-start", (_event, data) => callback(data)),
    onChatEnd: (callback) => ipcRenderer.on("nvidia-nim-chat-end", (_event, data) => callback(data)),
  }),
  openrouter: Object.freeze({
    status: () => ipcRenderer.invoke("openrouter-status"),
    models: () => ipcRenderer.invoke("openrouter-models"),
    getSettings: () => ipcRenderer.invoke("openrouter-settings-get"),
    saveSettings: (settings) => ipcRenderer.invoke("openrouter-settings-save", settings),
    chat: (payload) => ipcRenderer.invoke("openrouter-chat", payload),
    cancel: (sessionId) => ipcRenderer.invoke("openrouter-cancel", sessionId),
    onChunk: (callback) => ipcRenderer.on("openrouter-chunk", (_event, data) => callback(data)),
    onRetry: (callback) => ipcRenderer.on("openrouter-retry", (_event, data) => callback(data)),
    onTool: (callback) => ipcRenderer.on("openrouter-tool", (_event, data) => callback(data)),
    onToolResult: (callback) => ipcRenderer.on("openrouter-tool-result", (_event, data) => callback(data)),
    approveTool: (approvalId, approved) => ipcRenderer.invoke("openrouter-tool-approval", approvalId, approved),
    onToolApproval: (callback) => ipcRenderer.on("openrouter-tool-approval", (_event, data) => callback(data)),
    onChatStart: (callback) => ipcRenderer.on("openrouter-chat-start", (_event, data) => callback(data)),
  }),
  pty: Object.freeze({
    list: () => ipcRenderer.invoke("pty-list"),
    create: (options) => ipcRenderer.invoke("pty-create", options),
    write: (id, data) => ipcRenderer.invoke("pty-write", { id, data }),
    resize: (id, cols, rows) => ipcRenderer.invoke("pty-resize", { id, cols, rows }),
    stop: (id) => ipcRenderer.invoke("pty-stop", { id }),
    restart: (id) => ipcRenderer.invoke("pty-restart", { id }),
    close: (id) => ipcRenderer.invoke("pty-close", { id }),
    getBuffer: (id) => ipcRenderer.invoke("pty-buffer", { id }),
    getHistory: () => ipcRenderer.invoke("pty-history"),
    onEvent: (callback) => ipcRenderer.on("pty-event", (_event, value) => callback(value)),
    onActivity: (callback) => ipcRenderer.on("pty-activity", (_event, value) => callback(value)),
    onActivityUpdate: (callback) => ipcRenderer.on("pty-activity-update", (_event, value) => callback(value)),
  }),
  onHostExit: (callback) => ipcRenderer.on("host-exit", (_event, code) => callback(code)),
}));
